# Makefile for Data Analysis library
#
# $Id: Makefile,v 1.23 1998/07/02 01:06:42 granat Exp granat $
#
# $Log: Makefile,v $
# Revision 1.23  1998/07/02 01:06:42  granat
# checking in temporary hack by agray
#
# Revision 1.22  1998/04/20 22:42:24  roden
# - Simplified $(LIBRARY) rule so that Gnu make doesn't call ar unnecessarily.
# - Removed %.o rule all together since implicit rule was being used mostly,
#   and explicit rule caused two compilations under certain circumstances,
#   not to mention $(OUTPUT_OPTION) was screwing things up under Linux.
#
# Revision 1.21  1998/04/20 22:41:37  roden
# *** empty log message ***
#
# Revision 1.20  1997/07/31 21:59:06  agray
# added da_memory, alphabetized list of sources and headers, added makedepend
#
# Revision 1.19  1997/06/26 15:09:33  granat
# took out special mpi includes
#
# Revision 1.18  1997/06/26 00:06:35  granat
# added mpi includes, change later when mpich gets set up properly
#
# Revision 1.17  1997/06/20 20:39:27  granat
# added da_nrhacks, da_optim, da_geom
#
# Revision 1.16  1997/05/13 23:50:26  agray
# tons of changes.
#
# Revision 1.15  1996/10/31 02:47:40  agray
# updated after overhaul of library, which included renaming of modules.
#
# Revision 1.14  1996/09/23 23:58:03  agray
# added PVM properly, added -Wall to standard debug compile options.
#
# Revision 1.13  1996/09/23 23:08:29  granat
# Added inclusion of pvm include directory
#
# Revision 1.12  1996/09/23 23:02:23  agray
# un-commented parallel modules.
#
# Revision 1.11  1996/08/28 20:37:16  agray
# udpated list of modules - .c's and .h's.
#
# Revision 1.10  1996/07/15 18:18:54  agray
# commented out parallel modules for now, until PVM works on Suns.
#
# Revision 1.9  1996/07/11 16:46:51  agray
# added parallel modules da_clust_pp and da_msg_pp.
#
# Revision 1.8  1996/05/23 23:23:03  granat
# cosmetic
# rg
#
# Revision 1.6  1996/05/06 23:18:49  agray
# updated for solaris port; added standard directory variables
#
# Revision 1.5  1996/04/30 21:34:44  agray
# added da_dist.c,h.
# ag
#
# Revision 1.4  1996/02/28 04:54:49  agray
# added da_data module
# ag
#
# Revision 1.3  1996/02/21 05:17:43  agray
# added da_prob.c,.h.
# ag
#
# Revision 1.2  1996/02/21  00:37:57  agray
# changed da.h to da_linalg.h
# ag
#
# Revision 1.1  1996/02/06  03:28:36  agray
# Initial revision
#

# Library, source code, and objects.

LIBRARY		= libda.a

DESTDIR		= $(C_CODE_HOME)/lib

SOURCES.c	= \
			da_cluster.c \
			da_geom.c \
			da_io.c \
			da_linalg.c \
			da_memory.c \
			da_nrhacks.c \
			da_optim.c \
			da_probstat.c \
			da_random.c \
			da_signal.c \
			da_timeseg.c \
			da_util.c
#			da_cluster_pp.c \
#			da_comm_pp.c \
#			da_io_pp.c \
#			da_signal_pp.c

SOURCES.h = \
			da_cluster.h \
			da_geom.h \
			da_io.h \
			da_linalg.h \
			da_memory.h \
			da_nrhacks.h \
			da_optim.h \
			da_probstat.h \
			da_random.h \
			da_signal.h \
			da_timeseg.h \
			da_util.h
#			da_cluster_pp.h \
#			da_comm_pp.h \
#			da_io_pp.h \
#			da_signal_pp.h

SOURCES 	= $(SOURCES.h) $(SOURCES.c)

OBJECTS 	= $(SOURCES.c:%.c=%.o)

# Compiler options.

CC			= $(DA_CC)
#CC			= purify $(DA_CC)
#CFLAGS		= $(DA_CFLAGS)
#CFLAGS		= -pg
CFLAGS          = -g -Wall
CPPFLAGS	= -I$(C_CODE_HOME)/include

# Special make commands.

.PRECIOUS:	$(LIBRARY)

# Standard targets.

all:		depend $(SOURCES) $(OBJECTS) $(LIBRARY) install
objects:	$(SOURCES) $(OBJECTS)
sources:	$(SOURCES)
test:		

install: 
			cp $(LIBRARY) $(DESTDIR)

clean:	
			/bin/rm -f core $(OBJECTS) $(LIBRARY)

depend:
			makedepend -I$(C_CODE_HOME)/include *.c

# Targets' dependencies.

$(LIBRARY):	$(OBJECTS)
			ar rv $@ $?
#			libtool -c -static -o $@ $?

# Using implicit .c.o compile rule

# Specific objects' dependencies.
# DO NOT DELETE THIS LINE -- make depend depends on it.

da_cluster.o: /usr/include/stdlib.h /usr/include/features.h
da_cluster.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_cluster.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_cluster.o: /usr/include/stdio.h /usr/include/bits/types.h
da_cluster.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_cluster.o: /usr/include/_G_config.h /usr/include/wchar.h
da_cluster.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_cluster.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_cluster.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_cluster.o: /usr/include/math.h /usr/include/bits/huge_val.h
da_cluster.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
da_cluster.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/float.h
da_cluster.o: /home/granat/libraries/c/include/ut_types.h
da_cluster.o: /home/granat/libraries/c/include/ut_error.h
da_cluster.o: /home/granat/libraries/c/include/ut_output.h
da_cluster.o: /home/granat/libraries/c/include/nr.h
da_cluster.o: /home/granat/libraries/c/include/nr_complex.h
da_cluster.o: /home/granat/libraries/c/include/nr_util.h da_util.h da_io.h
da_cluster.o: da_linalg.h da_probstat.h da_random.h da_cluster.h
da_cluster_pp.o: /usr/include/stdlib.h /usr/include/features.h
da_cluster_pp.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_cluster_pp.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_cluster_pp.o: /usr/include/stdio.h /usr/include/bits/types.h
da_cluster_pp.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_cluster_pp.o: /usr/include/_G_config.h /usr/include/wchar.h
da_cluster_pp.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_cluster_pp.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_cluster_pp.o: /usr/include/bits/stdio_lim.h
da_cluster_pp.o: /usr/include/bits/sys_errlist.h /usr/include/math.h
da_cluster_pp.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
da_cluster_pp.o: /usr/include/bits/mathcalls.h
da_cluster_pp.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/float.h
da_cluster_pp.o: /home/granat/libraries/c/include/ut_types.h
da_cluster_pp.o: /home/granat/libraries/c/include/ut_error.h
da_cluster_pp.o: /home/granat/libraries/c/include/ut_output.h
da_cluster_pp.o: /home/granat/libraries/c/include/nr.h
da_cluster_pp.o: /home/granat/libraries/c/include/nr_complex.h
da_cluster_pp.o: /home/granat/libraries/c/include/nr_util.h da_cluster.h
da_cluster_pp.o: da_comm_pp.h da_linalg.h da_random.h da_util.h da_io.h
da_cluster_pp.o: da_probstat.h da_cluster_pp.h
da_comm_pp.o: /usr/include/stdlib.h /usr/include/features.h
da_comm_pp.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_comm_pp.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_comm_pp.o: /usr/include/stdio.h /usr/include/bits/types.h
da_comm_pp.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_comm_pp.o: /usr/include/_G_config.h /usr/include/wchar.h
da_comm_pp.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_comm_pp.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_comm_pp.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_comm_pp.o: /usr/include/math.h /usr/include/bits/huge_val.h
da_comm_pp.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
da_comm_pp.o: /usr/include/time.h /usr/include/bits/time.h
da_comm_pp.o: /usr/include/string.h da_platform.h
da_comm_pp.o: /home/granat/libraries/c/include/ut_types.h
da_comm_pp.o: /home/granat/libraries/c/include/ut_error.h
da_comm_pp.o: /home/granat/libraries/c/include/ut_output.h da_comm_pp.h
da_geom.o: /usr/include/stdlib.h /usr/include/features.h
da_geom.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_geom.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_geom.o: /usr/include/stdio.h /usr/include/bits/types.h
da_geom.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_geom.o: /usr/include/_G_config.h /usr/include/wchar.h
da_geom.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_geom.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_geom.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_geom.o: /usr/include/math.h /usr/include/bits/huge_val.h
da_geom.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
da_geom.o: /home/granat/libraries/c/include/ut_error.h
da_geom.o: /home/granat/libraries/c/include/ut_output.h
da_geom.o: /home/granat/libraries/c/include/ut_string.h
da_geom.o: /home/granat/libraries/c/include/ut_platform.h
da_geom.o: /home/granat/libraries/c/include/ut_types.h
da_geom.o: /home/granat/libraries/c/include/nr.h
da_geom.o: /home/granat/libraries/c/include/nr_complex.h
da_geom.o: /home/granat/libraries/c/include/nr_util.h da_geom.h
da_io.o: /usr/include/stdlib.h /usr/include/features.h
da_io.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_io.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_io.o: /usr/include/stdio.h /usr/include/bits/types.h
da_io.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_io.o: /usr/include/_G_config.h /usr/include/wchar.h
da_io.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_io.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_io.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_io.o: /usr/include/string.h /usr/include/math.h
da_io.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
da_io.o: /usr/include/bits/mathcalls.h /usr/include/assert.h
da_io.o: /home/granat/libraries/c/include/ut_types.h
da_io.o: /home/granat/libraries/c/include/ut_error.h
da_io.o: /home/granat/libraries/c/include/ut_output.h
da_io.o: /home/granat/libraries/c/include/ut_file_io.h
da_io.o: /home/granat/libraries/c/include/ut_memory.h
da_io.o: /home/granat/libraries/c/include/nr.h
da_io.o: /home/granat/libraries/c/include/nr_complex.h
da_io.o: /home/granat/libraries/c/include/nr_util.h da_util.h da_memory.h
da_io.o: da_io.h
da_io_pp.o: /usr/include/stdlib.h /usr/include/features.h
da_io_pp.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_io_pp.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_io_pp.o: /usr/include/stdio.h /usr/include/bits/types.h
da_io_pp.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_io_pp.o: /usr/include/_G_config.h /usr/include/wchar.h
da_io_pp.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_io_pp.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_io_pp.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_io_pp.o: /usr/include/math.h /usr/include/bits/huge_val.h
da_io_pp.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
da_io_pp.o: /home/granat/libraries/c/include/ut_error.h
da_io_pp.o: /home/granat/libraries/c/include/ut_output.h
da_io_pp.o: /home/granat/libraries/c/include/ut_types.h da_io.h da_comm_pp.h
da_io_pp.o: da_io_pp.h
da_linalg.o: /usr/include/stdlib.h /usr/include/features.h
da_linalg.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_linalg.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_linalg.o: /usr/include/stdio.h /usr/include/bits/types.h
da_linalg.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_linalg.o: /usr/include/_G_config.h /usr/include/wchar.h
da_linalg.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_linalg.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_linalg.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_linalg.o: /usr/include/math.h /usr/include/bits/huge_val.h
da_linalg.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
da_linalg.o: /usr/include/string.h
da_linalg.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/float.h
da_linalg.o: /home/granat/libraries/c/include/ut_error.h
da_linalg.o: /home/granat/libraries/c/include/ut_math.h
da_linalg.o: /home/granat/libraries/c/include/ut_memory.h
da_linalg.o: /home/granat/libraries/c/include/ut_output.h
da_linalg.o: /home/granat/libraries/c/include/ut_string.h
da_linalg.o: /home/granat/libraries/c/include/ut_platform.h
da_linalg.o: /home/granat/libraries/c/include/ut_types.h
da_linalg.o: /home/granat/libraries/c/include/nr.h
da_linalg.o: /home/granat/libraries/c/include/nr_complex.h
da_linalg.o: /home/granat/libraries/c/include/nr_util.h da_util.h
da_linalg.o: da_nrhacks.h da_linalg.h
da_memory.o: /usr/include/stdio.h /usr/include/features.h
da_memory.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_memory.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_memory.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
da_memory.o: /usr/include/libio.h /usr/include/_G_config.h
da_memory.o: /usr/include/wchar.h /usr/include/bits/wchar.h
da_memory.o: /usr/include/gconv.h
da_memory.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_memory.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_memory.o: /usr/include/stdlib.h
da_memory.o: /home/granat/libraries/c/include/ut_types.h
da_memory.o: /home/granat/libraries/c/include/ut_error.h
da_memory.o: /home/granat/libraries/c/include/ut_output.h
da_memory.o: /home/granat/libraries/c/include/ut_memory.h
da_memory.o: /home/granat/libraries/c/include/nr.h
da_memory.o: /home/granat/libraries/c/include/nr_complex.h
da_memory.o: /home/granat/libraries/c/include/nr_util.h da_memory.h
da_nrhacks.o: /usr/include/stdlib.h /usr/include/features.h
da_nrhacks.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_nrhacks.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_nrhacks.o: /usr/include/stdio.h /usr/include/bits/types.h
da_nrhacks.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_nrhacks.o: /usr/include/_G_config.h /usr/include/wchar.h
da_nrhacks.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_nrhacks.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_nrhacks.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_nrhacks.o: /usr/include/math.h /usr/include/bits/huge_val.h
da_nrhacks.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
da_nrhacks.o: /usr/include/signal.h /usr/include/bits/sigset.h
da_nrhacks.o: /usr/include/bits/signum.h
da_nrhacks.o: /home/granat/libraries/c/include/ut_error.h
da_nrhacks.o: /home/granat/libraries/c/include/ut_output.h
da_nrhacks.o: /home/granat/libraries/c/include/ut_string.h
da_nrhacks.o: /home/granat/libraries/c/include/ut_platform.h
da_nrhacks.o: /home/granat/libraries/c/include/ut_types.h
da_nrhacks.o: /home/granat/libraries/c/include/nr.h
da_nrhacks.o: /home/granat/libraries/c/include/nr_complex.h
da_nrhacks.o: /home/granat/libraries/c/include/nr_util.h da_nrhacks.h
da_optim.o: /usr/include/stdlib.h /usr/include/features.h
da_optim.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_optim.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_optim.o: /usr/include/stdio.h /usr/include/bits/types.h
da_optim.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_optim.o: /usr/include/_G_config.h /usr/include/wchar.h
da_optim.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_optim.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_optim.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_optim.o: /usr/include/math.h /usr/include/bits/huge_val.h
da_optim.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
da_optim.o: /home/granat/libraries/c/include/ut_error.h
da_optim.o: /home/granat/libraries/c/include/ut_output.h
da_optim.o: /home/granat/libraries/c/include/ut_string.h
da_optim.o: /home/granat/libraries/c/include/ut_platform.h
da_optim.o: /home/granat/libraries/c/include/ut_types.h
da_optim.o: /home/granat/libraries/c/include/nr.h
da_optim.o: /home/granat/libraries/c/include/nr_complex.h
da_optim.o: /home/granat/libraries/c/include/nr_util.h da_random.h
da_optim.o: da_nrhacks.h da_optim.h
da_probstat.o: /usr/include/stdlib.h /usr/include/features.h
da_probstat.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_probstat.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_probstat.o: /usr/include/stdio.h /usr/include/bits/types.h
da_probstat.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_probstat.o: /usr/include/_G_config.h /usr/include/wchar.h
da_probstat.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_probstat.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_probstat.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_probstat.o: /usr/include/math.h /usr/include/bits/huge_val.h
da_probstat.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
da_probstat.o: /home/granat/libraries/c/include/ut_error.h
da_probstat.o: /home/granat/libraries/c/include/ut_math.h
da_probstat.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/float.h
da_probstat.o: /home/granat/libraries/c/include/ut_output.h
da_probstat.o: /home/granat/libraries/c/include/ut_string.h
da_probstat.o: /home/granat/libraries/c/include/ut_platform.h
da_probstat.o: /home/granat/libraries/c/include/ut_types.h
da_probstat.o: /home/granat/libraries/c/include/nr.h
da_probstat.o: /home/granat/libraries/c/include/nr_complex.h
da_probstat.o: /home/granat/libraries/c/include/nr_util.h da_util.h da_io.h
da_probstat.o: da_linalg.h da_random.h da_probstat.h
da_random.o: /usr/include/stdlib.h /usr/include/features.h
da_random.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_random.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_random.o: /usr/include/stdio.h /usr/include/bits/types.h
da_random.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_random.o: /usr/include/_G_config.h /usr/include/wchar.h
da_random.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_random.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_random.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_random.o: /usr/include/math.h /usr/include/bits/huge_val.h
da_random.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
da_random.o: /usr/include/time.h /usr/include/bits/time.h
da_random.o: /home/granat/libraries/c/include/ut_types.h
da_random.o: /home/granat/libraries/c/include/ut_string.h
da_random.o: /home/granat/libraries/c/include/ut_platform.h
da_random.o: /home/granat/libraries/c/include/ut_error.h
da_random.o: /home/granat/libraries/c/include/ut_output.h
da_random.o: /home/granat/libraries/c/include/nr.h
da_random.o: /home/granat/libraries/c/include/nr_complex.h
da_random.o: /home/granat/libraries/c/include/nr_util.h da_platform.h
da_random.o: da_random.h
da_signal.o: /usr/include/stdlib.h /usr/include/features.h
da_signal.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_signal.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_signal.o: /usr/include/stdio.h /usr/include/bits/types.h
da_signal.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_signal.o: /usr/include/_G_config.h /usr/include/wchar.h
da_signal.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_signal.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_signal.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_signal.o: /usr/include/math.h /usr/include/bits/huge_val.h
da_signal.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
da_signal.o: /home/granat/libraries/c/include/ut_error.h
da_signal.o: /home/granat/libraries/c/include/ut_output.h
da_signal.o: /home/granat/libraries/c/include/ut_string.h
da_signal.o: /home/granat/libraries/c/include/ut_platform.h
da_signal.o: /home/granat/libraries/c/include/ut_types.h
da_signal.o: /home/granat/libraries/c/include/nr.h
da_signal.o: /home/granat/libraries/c/include/nr_complex.h
da_signal.o: /home/granat/libraries/c/include/nr_util.h da.h da_platform.h
da_signal.o: da_util.h da_nrhacks.h da_cluster.h da_io.h da_linalg.h
da_signal.o: da_memory.h da_probstat.h da_random.h da_signal.h da_timeseg.h
da_signal.o: da_optim.h da_geom.h
da_signal_pp.o: /usr/include/stdlib.h /usr/include/features.h
da_signal_pp.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_signal_pp.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_signal_pp.o: /usr/include/stdio.h /usr/include/bits/types.h
da_signal_pp.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_signal_pp.o: /usr/include/_G_config.h /usr/include/wchar.h
da_signal_pp.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_signal_pp.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_signal_pp.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_signal_pp.o: /usr/include/math.h /usr/include/bits/huge_val.h
da_signal_pp.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
da_signal_pp.o: /home/granat/libraries/c/include/ut_error.h
da_signal_pp.o: /home/granat/libraries/c/include/ut_output.h
da_signal_pp.o: /home/granat/libraries/c/include/ut_types.h
da_signal_pp.o: /home/granat/libraries/c/include/nr.h
da_signal_pp.o: /home/granat/libraries/c/include/nr_complex.h
da_signal_pp.o: /home/granat/libraries/c/include/nr_util.h da_comm_pp.h
da_signal_pp.o: da_signal_pp.h
da_timeseg.o: /usr/include/stdlib.h /usr/include/features.h
da_timeseg.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_timeseg.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_timeseg.o: /usr/include/stdio.h /usr/include/bits/types.h
da_timeseg.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_timeseg.o: /usr/include/_G_config.h /usr/include/wchar.h
da_timeseg.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_timeseg.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_timeseg.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_timeseg.o: /usr/include/math.h /usr/include/bits/huge_val.h
da_timeseg.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
da_timeseg.o: /usr/include/string.h
da_timeseg.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/float.h
da_timeseg.o: /home/granat/libraries/c/include/ut_types.h
da_timeseg.o: /home/granat/libraries/c/include/ut_string.h
da_timeseg.o: /home/granat/libraries/c/include/ut_platform.h
da_timeseg.o: /home/granat/libraries/c/include/ut_error.h
da_timeseg.o: /home/granat/libraries/c/include/ut_output.h
da_timeseg.o: /home/granat/libraries/c/include/ut_memory.h
da_timeseg.o: /home/granat/libraries/c/include/nr.h
da_timeseg.o: /home/granat/libraries/c/include/nr_complex.h
da_timeseg.o: /home/granat/libraries/c/include/nr_util.h da_util.h da_io.h
da_timeseg.o: da_random.h da_linalg.h da_cluster.h da_probstat.h da_timeseg.h
da_util.o: /usr/include/stdlib.h /usr/include/features.h
da_util.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
da_util.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
da_util.o: /usr/include/stdio.h /usr/include/bits/types.h
da_util.o: /usr/include/bits/wordsize.h /usr/include/libio.h
da_util.o: /usr/include/_G_config.h /usr/include/wchar.h
da_util.o: /usr/include/bits/wchar.h /usr/include/gconv.h
da_util.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
da_util.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
da_util.o: /usr/include/math.h /usr/include/bits/huge_val.h
da_util.o: /usr/include/bits/mathdef.h /usr/include/bits/mathcalls.h
da_util.o: /usr/include/string.h /home/granat/libraries/c/include/ut_error.h
da_util.o: /home/granat/libraries/c/include/ut_math.h
da_util.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/float.h
da_util.o: /home/granat/libraries/c/include/ut_memory.h
da_util.o: /home/granat/libraries/c/include/ut_output.h
da_util.o: /home/granat/libraries/c/include/ut_string.h
da_util.o: /home/granat/libraries/c/include/ut_platform.h
da_util.o: /home/granat/libraries/c/include/ut_types.h
da_util.o: /home/granat/libraries/c/include/nr_util.h da_linalg.h da_util.h
