---
- name: download the code on backend
  hosts: backend
  become: true
  tasks:
    - name: source bashrc
      shell: source /etc/bashrc
    - name: copy code to backend
      copy:
        src: srv/GPS_Scripts/
        dest: /root/GPS_Scripts/
        owner: root
        group: root
        mode: 0644
    # - name: clone repository
    #   git: 
    #    repo: https://github.com/GeoGateway/GPS_Scripts.git
    #    dest: "{{ repo_dest }}"
    #    update: no
      # command: git clone "https://github.com/GeoGateway/GPS_Scripts.git" /root/
    - name: set permissions to executable
      command: chdir="{{ repo_dest }}/GPS_Scripts/RDAHMM" chmod -R 777 rdahmm3

  vars:
    repo_dest: /root/

