---
- name: upgrade python
  hosts: backend
  become: yes
  tasks:
    - name: install gcc
      yum: name=gcc state=latest
    - name: download python 2.7.12
      command: wget https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz
    - name: extract python
      command: tar -xf Python-2.7.12.tgz
    - name: install libsqlite3-dev for sqlite3
      yum: name=sqlite-devel state=latest
    - name: configure python
      shell: chdir="{{ python_dir }}" ./configure --enable-loadable-sqlite-extensions && make && make install
    - name: update yum to old python to prevent it from breaking
      command: sed -i 's/python/python2.4/g' /usr/bin/yum      
    - name: copy old python to backup
      command: cp /usr/bin/python /usr/bin/python_bak
    - name: replace existing and make a soft link of new python
      command: ln -f -s /usr/local/bin/python2.7 /usr/bin/python
    - name: download pip
      command: wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
    - name: install pip
      command: python get-pip.py

  vars:
    python_dir: /root/Python-2.7.12/