---
- name: install mongodb to backend
  hosts: backend
  become: yes
  tasks:
    - name: copy mongodb repository configuration file
      copy:
        src: srv/mongodb-org-3.0.repo
        dest: /etc/yum.repos.d/mongodb-org-3.0.repo
        owner: root
        group: root
        mode: 0644
    - name: install mongodb
      command: yum install -y mongodb-org
    - name: start mongodb
      command: service mongod start
