---
# tasks file for git
- name: upgrade system to latest packages
  yum: 
   name: '*'
   state: latest
- name: preprequsites for git
  yum: name={{ item }} state=latest
  with_items: "{{ git_prerequisites }}"
- name: installing gcc
  shell: yum -y install gcc perl-ExtUtils-MakeMaker

- name: download git
  command: chdir="{{ download_dir }}" wget https://www.kernel.org/pub/software/scm/git/git-2.7.4.tar.gz --no-check-certificate -O git-2.7.4.tar.gz
- name: extract git
  command: chdir="{{ download_dir }}" tar xzf git-2.7.4.tar.gz
- name:  make all
  command: chdir="{{ git_dir }}" make prefix=/usr/local/git all
- name: make install
  command: chdir="{{ git_dir }}" make prefix=/usr/local/git install
- name: add git to bashrc
  shell: echo "export PATH=$PATH:/usr/local/git/bin" >> /etc/bashrc
- name: source bashrc
  shell: source /etc/bashrc