# Makefile for UT library

# $Id: Makefile,v 1.5 1999/10/06 02:40:12 cataract Exp granat $
# $Log: Makefile,v $
# Revision 1.5  1999/10/06 02:40:12  cataract
# Added position-independent flags
#
# Revision 1.4  1998/04/20 22:40:27  roden
# - Simplified $(LIBRARY) rule so that Gnu make doesn't call ar unnecessarily.
# - Removed %.o rule all together since implicit rule was being used mostly,
#   and explicit rule caused two compilations under certain circumstances,
#   not to mention $(OUTPUT_OPTION) was screwing things up under Linux.
#
# Revision 1.3  1997/07/31 22:08:21  agray
# added makedepend facility.
#
# Revision 1.2  1997/07/31 22:04:33  granat
# added flags for profiler/purify
#
# Revision 1.1  1997/05/13 23:33:13  granat
# Initial revision
#
#

# Library, source code, and objects.

LIBRARY		= libut.a

DESTDIR		= $(C_CODE_HOME)/lib

SOURCES.c	= \
			ut_args.c \
			ut_error.c \
			ut_file_io.c \
			ut_math.c \
			ut_memory.c \
			ut_output.c \
			ut_platform.c \
			ut_string.c \
			ut_time.c \
			ut_types.c

SOURCES.h	= \
			ut_args.h \
			ut_error.h \
			ut_file_io.h \
			ut_math.h \
			ut_memory.h \
			ut_output.h \
			ut_platform.h \
			ut_string.h \
			ut_time.h \
			ut_types.h \
			ut.h

SOURCES 	= $(SOURCES.h) $(SOURCES.c)

OBJECTS 	= $(SOURCES.c:%.c=%.o)

# Compiler options.

CC		= $(UT_CC)
#CC		= purify $(UT_CC)
CFLAGS		= $(UT_CFLAGS)
#CFLAGS		= -pg $(UT_CFLAGS)
#CFLAGS		= $(UT_FLAGS) -fpic
CPPFLAGS	= -I$(C_CODE_HOME)/include

# Special make commands.

.PRECIOUS:	$(LIBRARY)

# Standard targets.

all:		depend $(SOURCES) $(OBJECTS) $(LIBRARY) install
objects:	$(SOURCES) $(OBJECTS)
sources:	$(SOURCES)
test:		

install: 
			cp $(LIBRARY) $(DESTDIR)

clean:
			/bin/rm -f core $(OBJECTS) $(LIBRARY)

depend:
			makedepend -I$(C_CODE_HOME)/include *.c

# Targets' dependencies.

$(LIBRARY):	$(OBJECTS)
			ar rv $@ $?
#			libtool -c -static -o $@ $?

# Using implicit .c.o compile rule

# Specific objects' dependencies.
# DO NOT DELETE THIS LINE -- make depend depends on it.

ut_args.o: /usr/include/stdio.h /usr/include/features.h
ut_args.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ut_args.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
ut_args.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
ut_args.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
ut_args.o: /usr/include/bits/wchar.h /usr/include/gconv.h
ut_args.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
ut_args.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
ut_args.o: /usr/include/string.h ut_output.h ut_error.h ut_string.h
ut_args.o: ut_platform.h ut_memory.h ut_args.h
ut_error.o: /usr/include/stdio.h /usr/include/features.h
ut_error.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ut_error.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
ut_error.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
ut_error.o: /usr/include/libio.h /usr/include/_G_config.h
ut_error.o: /usr/include/wchar.h /usr/include/bits/wchar.h
ut_error.o: /usr/include/gconv.h
ut_error.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
ut_error.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
ut_error.o: /usr/include/string.h ut_output.h ut_error.h
ut_math.o: /usr/include/stdio.h /usr/include/features.h
ut_math.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ut_math.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
ut_math.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
ut_math.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
ut_math.o: /usr/include/bits/wchar.h /usr/include/gconv.h
ut_math.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
ut_math.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
ut_math.o: /usr/include/string.h /usr/include/math.h
ut_math.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
ut_math.o: /usr/include/bits/mathcalls.h ut_error.h ut_output.h ut_math.h
ut_math.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/float.h
ut_memory.o: /usr/include/stdio.h /usr/include/features.h
ut_memory.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ut_memory.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
ut_memory.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
ut_memory.o: /usr/include/libio.h /usr/include/_G_config.h
ut_memory.o: /usr/include/wchar.h /usr/include/bits/wchar.h
ut_memory.o: /usr/include/gconv.h
ut_memory.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
ut_memory.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
ut_memory.o: /usr/include/stdlib.h ut_error.h ut_output.h ut_memory.h
ut_output.o: /usr/include/stdio.h /usr/include/features.h
ut_output.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ut_output.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
ut_output.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
ut_output.o: /usr/include/libio.h /usr/include/_G_config.h
ut_output.o: /usr/include/wchar.h /usr/include/bits/wchar.h
ut_output.o: /usr/include/gconv.h
ut_output.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
ut_output.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
ut_output.o: ut_error.h ut_output.h
ut_string.o: /usr/include/stdio.h /usr/include/features.h
ut_string.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ut_string.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
ut_string.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
ut_string.o: /usr/include/libio.h /usr/include/_G_config.h
ut_string.o: /usr/include/wchar.h /usr/include/bits/wchar.h
ut_string.o: /usr/include/gconv.h
ut_string.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
ut_string.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
ut_string.o: ut_error.h ut_platform.h ut_memory.h ut_output.h ut_string.h
ut_time.o: /usr/include/stdio.h /usr/include/features.h
ut_time.o: /usr/include/sys/cdefs.h /usr/include/gnu/stubs.h
ut_time.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stddef.h
ut_time.o: /usr/include/bits/types.h /usr/include/bits/wordsize.h
ut_time.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
ut_time.o: /usr/include/bits/wchar.h /usr/include/gconv.h
ut_time.o: /usr/lib64/gcc-lib/x86_64-suse-linux/3.2.2/include/stdarg.h
ut_time.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
ut_time.o: ut_time.h
